title: Data Permissions Catalogue
email: hello@projectsbyif.com
description: An evolving collection of design patterns for sharing data
baseurl: ""
url: "https://catalogue.projectsbyif.com"
twitter_username: projectsbyif
github_username:  projectsbyif

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  patterns:
    output: true
  category:
    output: true
